name: TMF Lab - Portal - CI/CD

on:
  pull_request:
  push:
    branches: [master]

jobs:
  portal-ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: success()
        run: |
          npm install

      - name: Check commit message
        if: success()
        uses: wagoid/commitlint-github-action@v1

      - name: Build app
        if: success()
        run: |
          run build:ci

      - name: Check Lint
        if: success()
        run: |
          npm run lint

      - name: Test Unit with coverage
        if: success()
        run: |
          npm run test:ci

      - name: Upload coverage in Coveralls
        if: success()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: portal
          path: dist

      - name: Download build
        if: success()
        uses: actions/download-artifact@v1
        with:
          name: portal

      - name: Preper and deploy on GitHub Pages
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run deploy:gh -- --name="martins86" --email="martins86@gmail.com" --no-silent
